#!/usr/bin/env bash
# install.sh — register this workspace with the cdr fish helper family.
#
# Usage:
#   ./install.sh                # install / refresh
#   ./install.sh --uninstall    # remove this workspace's entry and alias
#   ./install.sh --status       # report current state
#   ./install.sh --root PATH    # override autodetected workspace root
#   ./install.sh --prefix STR   # override workspace.conf PREFIX
#   ./install.sh -h | --help    # show this help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CDR_FISH_DIR="$SCRIPT_DIR/cdr-fish"
WORKSPACE_CONF="$SCRIPT_DIR/workspace.conf"

FISH_FUNCS_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/fish/functions"
REGISTRY_DIR="$HOME/.config/cdr"
REGISTRY="$REGISTRY_DIR/workspaces.conf"

if [[ -t 1 ]]; then
    GRN=$'\033[32m' YLW=$'\033[33m' RED=$'\033[31m' DIM=$'\033[2m' RST=$'\033[0m'
else
    GRN='' YLW='' RED='' DIM='' RST=''
fi

usage() { sed -n '2,/^$/{ s/^# \?//; p }' "$0"; }
die()   { printf '%serror:%s %s\n' "$RED" "$RST" "$*" >&2; exit 1; }
info()  { printf '%s::%s %s\n' "$GRN" "$RST" "$*"; }

ACTION="install"
OVERRIDE_ROOT=""
OVERRIDE_PREFIX=""
PREFIX_OVERRIDDEN=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --uninstall) ACTION="uninstall"; shift ;;
        --status)    ACTION="status"; shift ;;
        --root)      OVERRIDE_ROOT="$2"; shift 2 ;;
        --prefix)    OVERRIDE_PREFIX="$2"; PREFIX_OVERRIDDEN=1; shift 2 ;;
        -h|--help)   usage; exit 0 ;;
        *)           die "unknown argument: $1 (try --help)" ;;
    esac
done

[[ -f "$WORKSPACE_CONF" ]] || die "$WORKSPACE_CONF not found"

NAME=""
PREFIX=""
while IFS='=' read -r key value; do
    [[ "$key" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${key// }" ]] && continue
    key="${key// }"
    case "$key" in
        NAME)   NAME="$value" ;;
        PREFIX) PREFIX="$value" ;;
    esac
done < "$WORKSPACE_CONF"

[[ -n "$NAME" ]] || die "NAME not set in $WORKSPACE_CONF"
[[ "$NAME" =~ ^[a-z][a-z0-9_-]*$ ]] || die "NAME '$NAME' must match [a-z][a-z0-9_-]*"

ROOT="${OVERRIDE_ROOT:-$WORKSPACE_ROOT}"
[[ "$PREFIX_OVERRIDDEN" -eq 1 ]] && PREFIX="$OVERRIDE_PREFIX"

[[ -f "$ROOT/repos.conf" ]] || die "$ROOT/repos.conf not found — is --root correct?"

REGISTRY_ENTRY="$NAME|$ROOT|$PREFIX"

upsert_registry() {
    mkdir -p "$REGISTRY_DIR"
    local tmp="$REGISTRY.$$.tmp"
    {
        echo "# Registry of multi-repo workspaces for the cdr fish helpers."
        echo "# Auto-managed by <workspace>/tools/cdr/install.sh"
        echo "# Format: name|absolute-root|repos-prefix"
        if [[ -f "$REGISTRY" ]]; then
            while IFS= read -r line; do
                [[ -z "$line" ]] && continue
                [[ "$line" =~ ^[[:space:]]*# ]] && continue
                local entry_name="${line%%|*}"
                [[ "$entry_name" == "$NAME" ]] && continue
                printf '%s\n' "$line"
            done < "$REGISTRY"
        fi
        printf '%s\n' "$REGISTRY_ENTRY"
    } > "$tmp"
    mv "$tmp" "$REGISTRY"
}

remove_from_registry() {
    [[ -f "$REGISTRY" ]] || return 0
    local tmp="$REGISTRY.$$.tmp"
    {
        while IFS= read -r line; do
            if [[ -z "$line" ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
                printf '%s\n' "$line"; continue
            fi
            local entry_name="${line%%|*}"
            [[ "$entry_name" == "$NAME" ]] && continue
            printf '%s\n' "$line"
        done < "$REGISTRY"
    } > "$tmp"
    mv "$tmp" "$REGISTRY"
}

write_alias_file() {
    local target="$FISH_FUNCS_DIR/cdr-$NAME.fish"
    cat > "$target" <<FISHEOF
# Auto-generated by $WORKSPACE_ROOT/tools/cdr/install.sh
# Re-run that script to regenerate. Edits will be lost.
#
# One-line shim: canonical implementation in workspace cdr -w $NAME.
function cdr-$NAME --description "Fuzzy cd into the $NAME workspace"
    workspace cdr -w $NAME \$argv
end
FISHEOF
}

copy_helpers() {
    mkdir -p "$FISH_FUNCS_DIR"
    local f
    for f in "$CDR_FISH_DIR"/*.fish; do
        [[ -f "$f" ]] || continue
        cp -- "$f" "$FISH_FUNCS_DIR/$(basename "$f")"
    done
}

case "$ACTION" in
    install)
        info "Installing cdr for workspace '$NAME'"
        printf '   %sroot:%s    %s\n' "$DIM" "$RST" "$ROOT"
        printf '   %sprefix:%s  %s\n' "$DIM" "$RST" "${PREFIX:-(none)}"
        copy_helpers
        write_alias_file
        upsert_registry
        info "Done. Open a new fish shell or run:"
        echo "      functions -e cdr cdr-$NAME __cdr_paths_in __cdr_pick __cdr_paths_for __cdr_workspaces"
        echo "      then try: cdr-$NAME <fuzzy-name>   or   cdr <fuzzy-name>"
        ;;
    uninstall)
        info "Uninstalling cdr-$NAME"
        rm -f "$FISH_FUNCS_DIR/cdr-$NAME.fish"
        remove_from_registry
        info "Removed alias and registry entry."
        ;;
    status)
        printf '%sworkspace:%s   %s\n' "$DIM" "$RST" "$NAME"
        printf '%sroot:%s        %s\n' "$DIM" "$RST" "$ROOT"
        printf '%sprefix:%s      %s\n' "$DIM" "$RST" "${PREFIX:-(none)}"
        printf '%sregistry:%s    %s\n' "$DIM" "$RST" "$REGISTRY"
        if [[ -f "$REGISTRY" ]] && grep -q "^$NAME|" "$REGISTRY"; then
            printf '%sregistered:%s  %syes%s — %s\n' "$DIM" "$RST" "$GRN" "$RST" "$(grep "^$NAME|" "$REGISTRY")"
        else
            printf '%sregistered:%s  %sno%s\n' "$DIM" "$RST" "$YLW" "$RST"
        fi
        printf '%salias:%s       %s\n' "$DIM" "$RST" "$FISH_FUNCS_DIR/cdr-$NAME.fish"
        if [[ -f "$FISH_FUNCS_DIR/cdr-$NAME.fish" ]]; then
            printf '             %sinstalled%s\n' "$GRN" "$RST"
        else
            printf '             %snot installed%s\n' "$YLW" "$RST"
        fi
        ;;
esac
